INSERT INTO `Country` (`id`, `iso`, `name`, `nicename`, `iso3`, `numcode`, `phonecode`) VALUES
(REPLACE(UUID(),'-',''), 'AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4, 93),
(REPLACE(UUID(),'-',''), 'AX', 'ALAND ISLANDS', 'Aland Islands', 'ALA', 248, 358),
(REPLACE(UUID(),'-',''), 'AL', 'ALBANIA', 'Albania', 'ALB', 8, 355),
(REPLACE(UUID(),'-',''), 'DZ', 'ALGERIA', 'Algeria', 'DZA', 12, 213),
(REPLACE(UUID(),'-',''), 'AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16, 1684),
(REPLACE(UUID(),'-',''), 'AD', 'ANDORRA', 'Andorra', 'AND', 20, 376),
(REPLACE(UUID(),'-',''), 'AO', 'ANGOLA', 'Angola', 'AGO', 24, 244),
(REPLACE(UUID(),'-',''), 'AI', 'ANGUILLA', 'Anguilla', 'AIA', 660, 1264),
(REPLACE(UUID(),'-',''), 'AQ', 'ANTARCTICA', 'Antarctica', NULL, NULL, 0),
(REPLACE(UUID(),'-',''), 'AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28, 1268),
(REPLACE(UUID(),'-',''), 'AR', 'ARGENTINA', 'Argentina', 'ARG', 32, 54),
(REPLACE(UUID(),'-',''), 'AM', 'ARMENIA', 'Armenia', 'ARM', 51, 374),
(REPLACE(UUID(),'-',''), 'AW', 'ARUBA', 'Aruba', 'ABW', 533, 297),
(REPLACE(UUID(),'-',''), 'AP', 'ASIA PACIFIC REGION', 'Asia / Pacific Region', '0', 0, 0),
(REPLACE(UUID(),'-',''), 'AU', 'AUSTRALIA', 'Australia', 'AUS', 36, 61),
(REPLACE(UUID(),'-',''), 'AT', 'AUSTRIA', 'Austria', 'AUT', 40, 43),
(REPLACE(UUID(),'-',''), 'AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31, 994),
(REPLACE(UUID(),'-',''), 'BS', 'BAHAMAS', 'Bahamas', 'BHS', 44, 1242),
(REPLACE(UUID(),'-',''), 'BH', 'BAHRAIN', 'Bahrain', 'BHR', 48, 973),
(REPLACE(UUID(),'-',''), 'BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50, 880),
(REPLACE(UUID(),'-',''), 'BB', 'BARBADOS', 'Barbados', 'BRB', 52, 1246),
(REPLACE(UUID(),'-',''), 'BY', 'BELARUS', 'Belarus', 'BLR', 112, 375),
(REPLACE(UUID(),'-',''), 'BE', 'BELGIUM', 'Belgium', 'BEL', 56, 32),
(REPLACE(UUID(),'-',''), 'BZ', 'BELIZE', 'Belize', 'BLZ', 84, 501),
(REPLACE(UUID(),'-',''), 'BJ', 'BENIN', 'Benin', 'BEN', 204, 229),
(REPLACE(UUID(),'-',''), 'BM', 'BERMUDA', 'Bermuda', 'BMU', 60, 1441),
(REPLACE(UUID(),'-',''), 'BT', 'BHUTAN', 'Bhutan', 'BTN', 64, 975),
(REPLACE(UUID(),'-',''), 'BO', 'BOLIVIA', 'Bolivia', 'BOL', 68, 591),
(REPLACE(UUID(),'-',''), 'BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', 'Bonaire, Sint Eustatius and Saba', 'BES', 535, 599),
(REPLACE(UUID(),'-',''), 'BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70, 387),
(REPLACE(UUID(),'-',''), 'BW', 'BOTSWANA', 'Botswana', 'BWA', 72, 267),
(REPLACE(UUID(),'-',''), 'BV', 'BOUVET ISLAND', 'Bouvet Island', NULL, NULL, 0),
(REPLACE(UUID(),'-',''), 'BR', 'BRAZIL', 'Brazil', 'BRA', 76, 55),
(REPLACE(UUID(),'-',''), 'IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL, NULL, 246),
(REPLACE(UUID(),'-',''), 'BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96, 673),
(REPLACE(UUID(),'-',''), 'BG', 'BULGARIA', 'Bulgaria', 'BGR', 100, 359),
(REPLACE(UUID(),'-',''), 'BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854, 226),
(REPLACE(UUID(),'-',''), 'BI', 'BURUNDI', 'Burundi', 'BDI', 108, 257),
(REPLACE(UUID(),'-',''), 'KH', 'CAMBODIA', 'Cambodia', 'KHM', 116, 855),
(REPLACE(UUID(),'-',''), 'CM', 'CAMEROON', 'Cameroon', 'CMR', 120, 237),
(REPLACE(UUID(),'-',''), 'CA', 'CANADA', 'Canada', 'CAN', 124, 1),
(REPLACE(UUID(),'-',''), 'CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132, 238),
(REPLACE(UUID(),'-',''), 'KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136, 1345),
(REPLACE(UUID(),'-',''), 'CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140, 236),
(REPLACE(UUID(),'-',''), 'TD', 'CHAD', 'Chad', 'TCD', 148, 235),
(REPLACE(UUID(),'-',''), 'CL', 'CHILE', 'Chile', 'CHL', 152, 56),
(REPLACE(UUID(),'-',''), 'CN', 'CHINA', 'China', 'CHN', 156, 86),
(REPLACE(UUID(),'-',''), 'CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, NULL, 61),
(REPLACE(UUID(),'-',''), 'CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL, 672),
(REPLACE(UUID(),'-',''), 'CO', 'COLOMBIA', 'Colombia', 'COL', 170, 57),
(REPLACE(UUID(),'-',''), 'KM', 'COMOROS', 'Comoros', 'COM', 174, 269),
(REPLACE(UUID(),'-',''), 'CG', 'CONGO', 'Congo', 'COG', 178, 242),
(REPLACE(UUID(),'-',''), 'CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 180, 242),
(REPLACE(UUID(),'-',''), 'CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184, 682),
(REPLACE(UUID(),'-',''), 'CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188, 506),
(REPLACE(UUID(),'-',''), 'CI', 'COTE D''IVOIRE', 'Cote D''Ivoire', 'CIV', 384, 225),
(REPLACE(UUID(),'-',''), 'HR', 'CROATIA', 'Croatia', 'HRV', 191, 385),
(REPLACE(UUID(),'-',''), 'CU', 'CUBA', 'Cuba', 'CUB', 192, 53),
(REPLACE(UUID(),'-',''), 'CW', 'CURACAO', 'Curacao', 'CUW', 531, 599),
(REPLACE(UUID(),'-',''), 'CY', 'CYPRUS', 'Cyprus', 'CYP', 196, 357),
(REPLACE(UUID(),'-',''), 'CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 203, 420),
(REPLACE(UUID(),'-',''), 'DK', 'DENMARK', 'Denmark', 'DNK', 208, 45),
(REPLACE(UUID(),'-',''), 'DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262, 253),
(REPLACE(UUID(),'-',''), 'DM', 'DOMINICA', 'Dominica', 'DMA', 212, 1767),
(REPLACE(UUID(),'-',''), 'DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214, 1809),
(REPLACE(UUID(),'-',''), 'EC', 'ECUADOR', 'Ecuador', 'ECU', 218, 593),
(REPLACE(UUID(),'-',''), 'EG', 'EGYPT', 'Egypt', 'EGY', 818, 20),
(REPLACE(UUID(),'-',''), 'SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222, 503),
(REPLACE(UUID(),'-',''), 'GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226, 240),
(REPLACE(UUID(),'-',''), 'ER', 'ERITREA', 'Eritrea', 'ERI', 232, 291),
(REPLACE(UUID(),'-',''), 'EE', 'ESTONIA', 'Estonia', 'EST', 233, 372),
(REPLACE(UUID(),'-',''), 'ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231, 251),
(REPLACE(UUID(),'-',''), 'FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238, 500),
(REPLACE(UUID(),'-',''), 'FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 234, 298),
(REPLACE(UUID(),'-',''), 'FJ', 'FIJI', 'Fiji', 'FJI', 242, 679),
(REPLACE(UUID(),'-',''), 'FI', 'FINLAND', 'Finland', 'FIN', 246, 358),
(REPLACE(UUID(),'-',''), 'FR', 'FRANCE', 'France', 'FRA', 250, 33),
(REPLACE(UUID(),'-',''), 'GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254, 594),
(REPLACE(UUID(),'-',''), 'PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258, 689),
(REPLACE(UUID(),'-',''), 'TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, NULL, 0),
(REPLACE(UUID(),'-',''), 'GA', 'GABON', 'Gabon', 'GAB', 266, 241),
(REPLACE(UUID(),'-',''), 'GM', 'GAMBIA', 'Gambia', 'GMB', 270, 220),
(REPLACE(UUID(),'-',''), 'GE', 'GEORGIA', 'Georgia', 'GEO', 268, 995),
(REPLACE(UUID(),'-',''), 'DE', 'GERMANY', 'Germany', 'DEU', 276, 49),
(REPLACE(UUID(),'-',''), 'GH', 'GHANA', 'Ghana', 'GHA', 288, 233),
(REPLACE(UUID(),'-',''), 'GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292, 350),
(REPLACE(UUID(),'-',''), 'GR', 'GREECE', 'Greece', 'GRC', 300, 30),
(REPLACE(UUID(),'-',''), 'GL', 'GREENLAND', 'Greenland', 'GRL', 304, 299),
(REPLACE(UUID(),'-',''), 'GD', 'GRENADA', 'Grenada', 'GRD', 308, 1473),
(REPLACE(UUID(),'-',''), 'GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312, 590),
(REPLACE(UUID(),'-',''), 'GU', 'GUAM', 'Guam', 'GUM', 316, 1671),
(REPLACE(UUID(),'-',''), 'GT', 'GUATEMALA', 'Guatemala', 'GTM', 320, 502),
(REPLACE(UUID(),'-',''), 'GG', 'GUERNSEY', 'Guernsey', 'GGY', 831, 44),
(REPLACE(UUID(),'-',''), 'GN', 'GUINEA', 'Guinea', 'GIN', 324, 224),
(REPLACE(UUID(),'-',''), 'GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624, 245),
(REPLACE(UUID(),'-',''), 'GY', 'GUYANA', 'Guyana', 'GUY', 328, 592),
(REPLACE(UUID(),'-',''), 'HT', 'HAITI', 'Haiti', 'HTI', 332, 509),
(REPLACE(UUID(),'-',''), 'HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', NULL, NULL, 0),
(REPLACE(UUID(),'-',''), 'VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 336, 39),
(REPLACE(UUID(),'-',''), 'HN', 'HONDURAS', 'Honduras', 'HND', 340, 504),
(REPLACE(UUID(),'-',''), 'HK', 'HONG KONG', 'Hong Kong', 'HKG', 344, 852),
(REPLACE(UUID(),'-',''), 'HU', 'HUNGARY', 'Hungary', 'HUN', 348, 36),
(REPLACE(UUID(),'-',''), 'IS', 'ICELAND', 'Iceland', 'ISL', 352, 354),
(REPLACE(UUID(),'-',''), 'IN', 'INDIA', 'India', 'IND', 356, 91),
(REPLACE(UUID(),'-',''), 'ID', 'INDONESIA', 'Indonesia', 'IDN', 360, 62),
(REPLACE(UUID(),'-',''), 'IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364, 98),
(REPLACE(UUID(),'-',''), 'IQ', 'IRAQ', 'Iraq', 'IRQ', 368, 964),
(REPLACE(UUID(),'-',''), 'IE', 'IRELAND', 'Ireland', 'IRL', 372, 353),
(REPLACE(UUID(),'-',''), 'IM', 'ISLE OF MAN', 'Isle of Man', 'IMN', 833, 44),
(REPLACE(UUID(),'-',''), 'IL', 'ISRAEL', 'Israel', 'ISR', 376, 972),
(REPLACE(UUID(),'-',''), 'IT', 'ITALY', 'Italy', 'ITA', 380, 39),
(REPLACE(UUID(),'-',''), 'JM', 'JAMAICA', 'Jamaica', 'JAM', 388, 1876),
(REPLACE(UUID(),'-',''), 'JP', 'JAPAN', 'Japan', 'JPN', 392, 81),
(REPLACE(UUID(),'-',''), 'JE', 'JERSEY', 'Jersey', 'JEY', 832, 44),
(REPLACE(UUID(),'-',''), 'JO', 'JORDAN', 'Jordan', 'JOR', 400, 962),
(REPLACE(UUID(),'-',''), 'KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398, 7),
(REPLACE(UUID(),'-',''), 'KE', 'KENYA', 'Kenya', 'KEN', 404, 254),
(REPLACE(UUID(),'-',''), 'KI', 'KIRIBATI', 'Kiribati', 'KIR', 296, 686),
(REPLACE(UUID(),'-',''), 'KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', 408, 850),
(REPLACE(UUID(),'-',''), 'KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 410, 82),
(REPLACE(UUID(),'-',''), 'XK', 'KOSOVO', 'Kosovo', '---', 0, 381),
(REPLACE(UUID(),'-',''), 'KW', 'KUWAIT', 'Kuwait', 'KWT', 414, 965),
(REPLACE(UUID(),'-',''), 'KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417, 996),
(REPLACE(UUID(),'-',''), 'LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', 418, 856),
(REPLACE(UUID(),'-',''), 'LV', 'LATVIA', 'Latvia', 'LVA', 428, 371),
(REPLACE(UUID(),'-',''), 'LB', 'LEBANON', 'Lebanon', 'LBN', 422, 961),
(REPLACE(UUID(),'-',''), 'LS', 'LESOTHO', 'Lesotho', 'LSO', 426, 266),
(REPLACE(UUID(),'-',''), 'LR', 'LIBERIA', 'Liberia', 'LBR', 430, 231),
(REPLACE(UUID(),'-',''), 'LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434, 218),
(REPLACE(UUID(),'-',''), 'LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438, 423),
(REPLACE(UUID(),'-',''), 'LT', 'LITHUANIA', 'Lithuania', 'LTU', 440, 370),
(REPLACE(UUID(),'-',''), 'LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442, 352),
(REPLACE(UUID(),'-',''), 'MO', 'MACAO', 'Macao', 'MAC', 446, 853),
(REPLACE(UUID(),'-',''), 'MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807, 389),
(REPLACE(UUID(),'-',''), 'MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450, 261),
(REPLACE(UUID(),'-',''), 'MW', 'MALAWI', 'Malawi', 'MWI', 454, 265),
(REPLACE(UUID(),'-',''), 'MY', 'MALAYSIA', 'Malaysia', 'MYS', 458, 60),
(REPLACE(UUID(),'-',''), 'MV', 'MALDIVES', 'Maldives', 'MDV', 462, 960),
(REPLACE(UUID(),'-',''), 'ML', 'MALI', 'Mali', 'MLI', 466, 223),
(REPLACE(UUID(),'-',''), 'MT', 'MALTA', 'Malta', 'MLT', 470, 356),
(REPLACE(UUID(),'-',''), 'MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584, 692),
(REPLACE(UUID(),'-',''), 'MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474, 596),
(REPLACE(UUID(),'-',''), 'MR', 'MAURITANIA', 'Mauritania', 'MRT', 478, 222),
(REPLACE(UUID(),'-',''), 'MU', 'MAURITIUS', 'Mauritius', 'MUS', 480, 230),
(REPLACE(UUID(),'-',''), 'YT', 'MAYOTTE', 'Mayotte', NULL, NULL, 269),
(REPLACE(UUID(),'-',''), 'MX', 'MEXICO', 'Mexico', 'MEX', 484, 52),
(REPLACE(UUID(),'-',''), 'FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583, 691),
(REPLACE(UUID(),'-',''), 'MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 498, 373),
(REPLACE(UUID(),'-',''), 'MC', 'MONACO', 'Monaco', 'MCO', 492, 377),
(REPLACE(UUID(),'-',''), 'MN', 'MONGOLIA', 'Mongolia', 'MNG', 496, 976),
(REPLACE(UUID(),'-',''), 'ME', 'MONTENEGRO', 'Montenegro', 'MNE', 499, 382),
(REPLACE(UUID(),'-',''), 'MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500, 1664),
(REPLACE(UUID(),'-',''), 'MA', 'MOROCCO', 'Morocco', 'MAR', 504, 212),
(REPLACE(UUID(),'-',''), 'MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508, 258),
(REPLACE(UUID(),'-',''), 'MM', 'MYANMAR', 'Myanmar', 'MMR', 104, 95),
(REPLACE(UUID(),'-',''), 'NA', 'NAMIBIA', 'Namibia', 'NAM', 516, 264),
(REPLACE(UUID(),'-',''), 'NR', 'NAURU', 'Nauru', 'NRU', 520, 674),
(REPLACE(UUID(),'-',''), 'NP', 'NEPAL', 'Nepal', 'NPL', 524, 977),
(REPLACE(UUID(),'-',''), 'NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528, 31),
(REPLACE(UUID(),'-',''), 'AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530, 599),
(REPLACE(UUID(),'-',''), 'NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540, 687),
(REPLACE(UUID(),'-',''), 'NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554, 64),
(REPLACE(UUID(),'-',''), 'NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558, 505),
(REPLACE(UUID(),'-',''), 'NE', 'NIGER', 'Niger', 'NER', 562, 227),
(REPLACE(UUID(),'-',''), 'NG', 'NIGERIA', 'Nigeria', 'NGA', 566, 234),
(REPLACE(UUID(),'-',''), 'NU', 'NIUE', 'Niue', 'NIU', 570, 683),
(REPLACE(UUID(),'-',''), 'NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574, 672),
(REPLACE(UUID(),'-',''), 'MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580, 1670),
(REPLACE(UUID(),'-',''), 'NO', 'NORWAY', 'Norway', 'NOR', 578, 47),
(REPLACE(UUID(),'-',''), 'OM', 'OMAN', 'Oman', 'OMN', 512, 968),
(REPLACE(UUID(),'-',''), 'PK', 'PAKISTAN', 'Pakistan', 'PAK', 586, 92),
(REPLACE(UUID(),'-',''), 'PW', 'PALAU', 'Palau', 'PLW', 585, 680),
(REPLACE(UUID(),'-',''), 'PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, NULL, 970),
(REPLACE(UUID(),'-',''), 'PA', 'PANAMA', 'Panama', 'PAN', 591, 507),
(REPLACE(UUID(),'-',''), 'PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598, 675),
(REPLACE(UUID(),'-',''), 'PY', 'PARAGUAY', 'Paraguay', 'PRY', 600, 595),
(REPLACE(UUID(),'-',''), 'PE', 'PERU', 'Peru', 'PER', 604, 51),
(REPLACE(UUID(),'-',''), 'PH', 'PHILIPPINES', 'Philippines', 'PHL', 608, 63),
(REPLACE(UUID(),'-',''), 'PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612, 0),
(REPLACE(UUID(),'-',''), 'PL', 'POLAND', 'Poland', 'POL', 616, 48),
(REPLACE(UUID(),'-',''), 'PT', 'PORTUGAL', 'Portugal', 'PRT', 620, 351),
(REPLACE(UUID(),'-',''), 'PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630, 1787),
(REPLACE(UUID(),'-',''), 'QA', 'QATAR', 'Qatar', 'QAT', 634, 974),
(REPLACE(UUID(),'-',''), 'RE', 'REUNION', 'Reunion', 'REU', 638, 262),
(REPLACE(UUID(),'-',''), 'RO', 'ROMANIA', 'Romania', 'ROM', 642, 40),
(REPLACE(UUID(),'-',''), 'RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643, 70),
(REPLACE(UUID(),'-',''), 'RW', 'RWANDA', 'Rwanda', 'RWA', 646, 250),
(REPLACE(UUID(),'-',''), 'SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654, 290),
(REPLACE(UUID(),'-',''), 'KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659, 1869),
(REPLACE(UUID(),'-',''), 'LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662, 1758),
(REPLACE(UUID(),'-',''), 'PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666, 508),
(REPLACE(UUID(),'-',''), 'VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670, 1784),
(REPLACE(UUID(),'-',''), 'WS', 'SAMOA', 'Samoa', 'WSM', 882, 684),
(REPLACE(UUID(),'-',''), 'SM', 'SAN MARINO', 'San Marino', 'SMR', 674, 378),
(REPLACE(UUID(),'-',''), 'ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678, 239),
(REPLACE(UUID(),'-',''), 'BL', 'SAINT BARTHELEMY', 'Saint Barthelemy', 'BLM', 652, 590),
(REPLACE(UUID(),'-',''), 'MF', 'SAINT MARTIN', 'Saint Martin', 'MAF', 663, 590),
(REPLACE(UUID(),'-',''), 'SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682, 966),
(REPLACE(UUID(),'-',''), 'SN', 'SENEGAL', 'Senegal', 'SEN', 686, 221),
(REPLACE(UUID(),'-',''), 'RS', 'SERBIA', 'Serbia', 'SRB', 688, 381),
(REPLACE(UUID(),'-',''), 'SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690, 248),
(REPLACE(UUID(),'-',''), 'SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694, 232),
(REPLACE(UUID(),'-',''), 'SG', 'SINGAPORE', 'Singapore', 'SGP', 702, 65),
(REPLACE(UUID(),'-',''), 'SX', 'SINT MAARTEN', 'Sint Maarten', 'SXM', 534, 1),
(REPLACE(UUID(),'-',''), 'SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703, 421),
(REPLACE(UUID(),'-',''), 'SI', 'SLOVENIA', 'Slovenia', 'SVN', 705, 386),
(REPLACE(UUID(),'-',''), 'SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90, 677),
(REPLACE(UUID(),'-',''), 'SO', 'SOMALIA', 'Somalia', 'SOM', 706, 252),
(REPLACE(UUID(),'-',''), 'ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710, 27),
(REPLACE(UUID(),'-',''), 'GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', NULL, NULL, 0),
(REPLACE(UUID(),'-',''), 'ES', 'SPAIN', 'Spain', 'ESP', 724, 34),
(REPLACE(UUID(),'-',''), 'LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144, 94),
(REPLACE(UUID(),'-',''), 'SD', 'SUDAN', 'Sudan', 'SDN', 736, 249),
(REPLACE(UUID(),'-',''), 'SS', 'SOUTH SUDAN', 'South Sudan', 'SSD', 728, 211),
(REPLACE(UUID(),'-',''), 'SR', 'SURINAME', 'Suriname', 'SUR', 740, 597),
(REPLACE(UUID(),'-',''), 'SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', 744, 47),
(REPLACE(UUID(),'-',''), 'SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748, 268),
(REPLACE(UUID(),'-',''), 'SE', 'SWEDEN', 'Sweden', 'SWE', 752, 46),
(REPLACE(UUID(),'-',''), 'CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756, 41),
(REPLACE(UUID(),'-',''), 'SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760, 963),
(REPLACE(UUID(),'-',''), 'TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 158, 886),
(REPLACE(UUID(),'-',''), 'TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762, 992),
(REPLACE(UUID(),'-',''), 'TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 834, 255),
(REPLACE(UUID(),'-',''), 'TH', 'THAILAND', 'Thailand', 'THA', 764, 66),
(REPLACE(UUID(),'-',''), 'TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, NULL, 670),
(REPLACE(UUID(),'-',''), 'TG', 'TOGO', 'Togo', 'TGO', 768, 228),
(REPLACE(UUID(),'-',''), 'TK', 'TOKELAU', 'Tokelau', 'TKL', 772, 690),
(REPLACE(UUID(),'-',''), 'TO', 'TONGA', 'Tonga', 'TON', 776, 676),
(REPLACE(UUID(),'-',''), 'TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780, 1868),
(REPLACE(UUID(),'-',''), 'TN', 'TUNISIA', 'Tunisia', 'TUN', 788, 216),
(REPLACE(UUID(),'-',''), 'TR', 'TURKEY', 'Turkey', 'TUR', 792, 90),
(REPLACE(UUID(),'-',''), 'TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795, 7370),
(REPLACE(UUID(),'-',''), 'TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796, 1649),
(REPLACE(UUID(),'-',''), 'TV', 'TUVALU', 'Tuvalu', 'TUV', 798, 688),
(REPLACE(UUID(),'-',''), 'UG', 'UGANDA', 'Uganda', 'UGA', 800, 256),
(REPLACE(UUID(),'-',''), 'UA', 'UKRAINE', 'Ukraine', 'UKR', 804, 380),
(REPLACE(UUID(),'-',''), 'AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784, 971),
(REPLACE(UUID(),'-',''), 'GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 826, 44),
(REPLACE(UUID(),'-',''), 'US', 'UNITED STATES', 'United States', 'USA', 840, 1),
(REPLACE(UUID(),'-',''), 'UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', NULL, NULL, 1),
(REPLACE(UUID(),'-',''), 'UY', 'URUGUAY', 'Uruguay', 'URY', 858, 598),
(REPLACE(UUID(),'-',''), 'UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860, 998),
(REPLACE(UUID(),'-',''), 'VU', 'VANUATU', 'Vanuatu', 'VUT', 548, 678),
(REPLACE(UUID(),'-',''), 'VE', 'VENEZUELA', 'Venezuela', 'VEN', 862, 58),
(REPLACE(UUID(),'-',''), 'VN', 'VIET NAM', 'Viet Nam', 'VNM', 704, 84),
(REPLACE(UUID(),'-',''), 'VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 92, 1284),
(REPLACE(UUID(),'-',''), 'VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', 850, 1340),
(REPLACE(UUID(),'-',''), 'WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', 876, 681),
(REPLACE(UUID(),'-',''), 'EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732, 212),
(REPLACE(UUID(),'-',''), 'YE', 'YEMEN', 'Yemen', 'YEM', 887, 967),
(REPLACE(UUID(),'-',''), 'ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894, 260),
(REPLACE(UUID(),'-',''), 'ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716, 263);